# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  db.vm.provision "docker" do |d|
    # Host    : 127.0.0.1:5432
    # Username: postgres
    # Password: banaan
    d.run "postgresql",
      image: "tutum/postgresql",
      daemonize: true,
      args: "-p 5432:5432 \
             -e POSTGRES_PASS='banaan'"

    # d.run "postgresql",
    #   image: "paintedfox/postgresql",
    #   daemonize: true,
    #   args: "-p 127.0.0.1:5432:5432 \
    #         -v /tmp/postgresql:/data \
    #         -e USER='postgres' \
    #         -e DB='UNWDMI' \
    #         -e PASS='banaan'"

    # d.build_image "/vagrant/Resources/import",
    #   args: "-t 'dbimport'"
    # d.run "postgresql_import",
    #   image: "dbimport",
    #   args: "--link postgresql:db"

    # d.pull_images "dockerfile/java"
  end
end
